lastupdatecheck: 0
recentrepos:
- /home/goose/Documents/Coding/Other/dotfiles
- /home/goose/Documents/Uni/semester-6summer/web23
- /home/goose/Documents/Uni
- /home/goose/Documents/Coding/Rust/copenhell-calendar
- /home/goose/Documents/Uni/semester-6/baps/projects/exam
- /home/goose/Documents/Coding/NodeJS/sanity-orm
- /home/goose/Documents/Coding/NodeJS/sanity-orm-db
- /home/goose/Documents/Coding/NodeJS/dagens-backend
- /home/goose/qmk_firmware/keyboards/sofle/keymaps/sofle-qmk
- /home/goose/Documents/Coding/Other/sofle-qmk
- /home/goose/Documents/Coding/Other/kattis-solutions
- /home/goose/Documents/Coding/Other/kubernetes-platform
- /home/goose/Documents/Coding/Other/zmk-adventures
- /home/goose/Documents/Coding/Other/kattis-checker
- /home/goose/Documents/Coding/Web/band-connector
- /home/goose/Documents/Coding/Other/job-searches
- /home/goose/Documents/Coding/Other/cv
- /home/goose/Documents/Coding/Other/arch-goose
- /home/goose/Documents/Uni/semester-5/BPRD/projects/exam
- /home/goose/Documents/Uni/semester-5/BPRD/projects/bprd-previous-exams
- /home/goose/Documents/Coding/Go/identilink
- /home/goose/Documents/Coding/Other/albe2669.github
- /home/goose/Documents/Coding/Rust/aoc-solutions
- /home/goose/qmk_firmware/keyboards/sofle/keymaps/albe2669
- /home/goose/Documents/Uni/semester-5/BOSC/projects/malloclab
- /home/goose/Documents/Uni/semester-5/BOSC/projects/datalab
- /home/goose/Documents/Coding/NodeJS/sanity-client
- /home/goose/.local/share/nvim/plugged/telekasten.nvim
- /home/goose/Documents/Coding/K8/todoapp
startuppopupversion: 5
customcommandshistory:
- q
- qa
hidecommandlog: false
