
[font.bold]
family = "IosevkaTerm Nerd Font"
style = "Bold"

[font.normal]
family = "IosevkaTerm Nerd Font"
style = "Regular"

[font.italic]
family = "IosevkaTerm Nerd Font"
style = "Italic"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "Return"
mods = "Command"

[general]
import = ["~/.config/alacritty/themes/theme.toml"]

