# Drop to shell
[[manager.prepend_keymap]]
on   = "!"
run  = 'shell "$SHELL" --block --confirm'
desc = "Open shell here"

# Smart directory
[[manager.prepend_keymap]]
on   = "l"
run  = "plugin --sync smart-enter"
desc = "Enter the child directory, or open the file"

# Smart paste
[[manager.prepend_keymap]]
on   = "p"
run  = "plugin --sync smart-paste"
desc = "Paste into the hovered directory or CWD"

# Smart copy
[[manager.prepend_keymap]]
on  = "y"
run = [ '''
	shell 'echo "$@" | pbcopy' --confirm
''', "yank" ]

# Git root dir
[[manager.prepend_keymap]]
on = [ "g", "r" ]
run = '''
	shell 'ya pub dds-cd --str "$(git rev-parse --show-toplevel)"' --confirm
'''

# Mac Quick Look bind
[[manager.prepend_keymap]]
on = "<C-p>"
run = '''
  shell 'qlmanage -p "$@"' --confirm
'''

# Chmod 
[[manager.prepend_keymap]]
on   = [ "c", "m" ]
run  = "plugin chmod"
desc = "Chmod on selected files"

# Create diff 
[[manager.prepend_keymap]]
on   = "<C-d>"
run  = "plugin diff"
desc = "Diff the selected with the hovered file"

# Calc size
[[manager.prepend_keymap]]
on   = [ ".", "s" ]
run  = "plugin what-size --args='--clipboard'"
desc = "Calc size of selection or cwd"

# Lazygit
[[manager.prepend_keymap]]
on   = [ "g", "i" ]
run  = "plugin lazygit"
desc = "run lazygit"

# Copy file contents
[[manager.prepend_keymap]]
on = "<C-c>"
run = ["plugin copy-file-contents"]
desc = "Copy contents of file"

# Smart filter
[[manager.prepend_keymap]]
on   = "F"
run  = "plugin smart-filter"
desc = "Smart filter"

# Toggle views
[[manager.prepend_keymap]]
on = "<C-1>"
run = "plugin --sync toggle-view --args=parent"
desc = "Toggle parent"

[[manager.prepend_keymap]]
on = "<C-2>" 
run = "plugin --sync toggle-view --args=current"
desc = "Toggle current"

[[manager.prepend_keymap]]
on = "<C-3>"
run = "plugin --sync toggle-view --args=preview"
desc = "Toggle preview"


## Relative motions plugin binds
[[manager.prepend_keymap]]
on = [ "1" ]
run = "plugin relative-motions --args=1"
desc = "Move in relative steps"

[[manager.prepend_keymap]]
on = [ "2" ]
run = "plugin relative-motions --args=2"
desc = "Move in relative steps"

[[manager.prepend_keymap]]
on = [ "3" ]
run = "plugin relative-motions --args=3"
desc = "Move in relative steps"

[[manager.prepend_keymap]]
on = [ "4" ]
run = "plugin relative-motions --args=4"
desc = "Move in relative steps"

[[manager.prepend_keymap]]
on = [ "5" ]
run = "plugin relative-motions --args=5"
desc = "Move in relative steps"

[[manager.prepend_keymap]]
on = [ "6" ]
run = "plugin relative-motions --args=6"
desc = "Move in relative steps"

[[manager.prepend_keymap]]
on = [ "7" ]
run = "plugin relative-motions --args=7"
desc = "Move in relative steps"

[[manager.prepend_keymap]]
on = [ "8" ]
run = "plugin relative-motions --args=8"
desc = "Move in relative steps"

[[manager.prepend_keymap]]
on = [ "9" ]
run = "plugin relative-motions --args=9"
desc = "Move in relative steps"

