[opener]
firefox = [
	{ run = 'firefox "$1"', desc = "Firefox" },
]

[open]
prepend_rules = [
  { mime = "image/*", use = [ "open", "firefox", "reveal" ] },
  { mime = "application/pdf", use = [ "firefox", "open", "reveal" ] },
]

[preview]
max_width = 1280
max_height = 1920

[manager]
show_hidden = true
show_symlink = true

[plugin]
prepend_previewers = [
  { name = "*.md", run = "glow" },
  { name = "*/", run = "eza-preview" },
]


[[manager.prepend_keymap]]
on   = [ "g", "i" ]
run  = "plugin lazygit"
desc = "run lazygit"
